version: '3.9'
services:
  db:
    container_name: FakeStoreDatabase
    image: mariadb
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    extra_hosts:
      - "host.docker.internal:host-gateway"
  server:
    container_name: FakeStoreServer
    build: ./server
    depends_on:
      - db
    ports:
      - '5000:5000'
  loadbalancer:
    container_name: FakeStoreLoadBalancer
    image: nginx
    ports:
      - '80:80'
    depends_on:
      - server
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
